# Generated by Django 4.2.6 on 2023-11-07 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_topics'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postagem',
            name='author',
        ),
    ]
